/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import java.util.List;

import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Attribute;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-07T17:59:04.303-07:00")

@Api(value = "attributes", description = "the attributes API")
public interface AttributesApi {

	@ApiOperation(value = "get file EDH attributes", notes = "get EDH attributes associated with the file parameter", response = Attribute.class, responseContainer = "List", tags = {})
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "list of file attributes", response = Attribute.class, responseContainer = "List"),
			@ApiResponse(code = 400, message = "Bad request", response = Void.class),
			@ApiResponse(code = 404, message = "Unable to locate file", response = Void.class) })

	@RequestMapping(value = "/attributes/{file}", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<Attribute>> attributesFileGet(
			@ApiParam(value = "Amazon Web Services (AWS)  Simple Storage Service (S3) Amazon Resource Name(ARN).  For example, arn:aws:s3:::my_data_bucket/data-file.tdo", required = true) @PathVariable("file") String file);

	@RequestMapping(value = "/attributes", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<Attribute>> attributesGet(
			@NotNull @ApiParam(value = "Amazon Web Services (AWS)  Simple Storage Service (S3) bucket name.", required = true) @RequestParam(value = "bucket", required = true) String bucket,
			@NotNull @ApiParam(value = "Amazon Web Services (AWS)  Simple Storage Service (S3) object key name.", required = true) @RequestParam(value = "key", required = true) String key);

}